development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:75ebe157f861ddd29129a5883aee4c92@barb.redistogo.com:9945/
  channel_prefix: backend_production
